### ISSUE TITLE
请问为什么点击周次切换之后，会发生卡顿呢？

### ISSUE THREAD

**Issue by iazhan** [zguolee/ColorTimetable#1]
请问为什么点击周次切换之后，会发生卡顿呢？

**Comment by zguolee** [comment]
显示和隐藏周选择吗？

----------

该邮件从移动设备发送











--------------原始邮件--------------
发件人："阿战 ***@***.***&gt;;
发送时间：2021年5月7日(星期五) 晚上10:40
收件人："zguolee/ColorTimetable" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[zguolee/ColorTimetable] 请问为什么点击周次切换之后，会发生卡顿呢？ (#1)
-----------------------------------

 

 
请问为什么点击周次切换之后，会发生卡顿呢？

**Comment by iazhan** [comment]
对

**Comment by zguolee** [comment]
每次数据渲染问题，暂时还未解决，可以把 v-if 换成 v-show 减少影响。
```
<!-- 周数切换 -->
- <view class="timetable-week" v-if="showTimetableWeek">
+ <view class="timetable-week" v-show="showTimetableWeek">
```
