### ISSUE TITLE
[plugin:unocss:transformers:pre] Cannot read properties of undefined (reading 'join') at pages/splash/splash.vue:1:0

### ISSUE THREAD

**Issue by Alpenl** [zguolee/ColorTimetable#19]
微信小程序报错：[plugin:unocss:transformers:pre] Cannot read properties of undefined (reading 'join')
at pages/splash/splash.vue:1:0

![image](https://github.com/user-attachments/assets/aec723b1-bfbc-48ab-b77f-bb9dce81c6ae)

**Comment by nei1ee** [comment]
这个已经不在维护了，有需要可以自己尝试修复下。

**Comment by sandof** [comment]
老哥解决了吗
求带 @Alpenl

**Comment by Alpenl** [comment]
没有，参考重写了
